// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerProfile.Infrastructure.Persistance.Context;

#nullable disable

namespace PlayerProfile.Infrastructure.Migrations
{
    [DbContext(typeof(PlayerProfileDbContext))]
    [Migration("20260406115629_AddGangSystem")]
    partial class AddGangSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerProfile.Domain.Entities.Gang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("LogoKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxMemberLimit")
                        .HasColumnType("int");

                    b.Property<int>("MemberCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("TotalRespectScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("Gangs", (string)null);
                });

            modelBuilder.Entity("PlayerProfile.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("GangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GangRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("HeatIndex")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEnergyCalcUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RespectScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.ComplexProperty<Dictionary<string, object>>("Energy", "PlayerProfile.Domain.Entities.Player.Energy#Energy", b1 =>
                        {
                            b1.Property<int>("Current")
                                .HasColumnType("int")
                                .HasColumnName("EnergyCurrent");

                            b1.Property<int>("Max")
                                .HasColumnType("int")
                                .HasColumnName("EnergyMax");

                            b1.Property<int>("RegenPerMinute")
                                .HasColumnType("int")
                                .HasColumnName("EnergyRegenPerMinute");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Rank", "PlayerProfile.Domain.Entities.Player.Rank#Rank", b1 =>
                        {
                            b1.Property<int?>("Position")
                                .HasColumnType("int")
                                .HasColumnName("RankPosition");

                            b1.Property<int>("RankPoints")
                                .HasColumnType("int")
                                .HasColumnName("RankPoints");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Stats", "PlayerProfile.Domain.Entities.Player.Stats#Stats", b1 =>
                        {
                            b1.Property<int>("Agility")
                                .HasColumnType("int")
                                .HasColumnName("Agility");

                            b1.Property<int>("Defense")
                                .HasColumnType("int")
                                .HasColumnName("Defense");

                            b1.Property<int>("Luck")
                                .HasColumnType("int")
                                .HasColumnName("Luck");

                            b1.Property<int>("Power")
                                .HasColumnType("int")
                                .HasColumnName("Power");
                        });

                    b.HasKey("Id");

                    b.ToTable("Players", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
